
name: First Workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print Good bye
        run: echo "Done Good Bye !!!"
